CREATE TABLE member(
	mail VARCHAR(100) PRIMARY KEY,
	user_name VARCHAR(30) NOT NULL CHECK(3 <= LENGTH(user_name)),
	pw VARCHAR(512) NOT NULL,
	phone VARCHAR(20) NULL,
	secondary_mail VARCHAR(100) NULL,
	valid BIT DEFAULT 1,
	pw_changed_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	rgdt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updt DATETIME DEFAULT CURRENT_TIMESTAMP
);
